### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by neu1886** [fire-eggs/YAGP#10]
@fire-eggs 

Hi, is it possible to post some screenshots of the different AnceDraw Diagrams? I am not coding with C#, but i am interessed, how the charts looks (Circle and 4/5 Generation Chart).

Thank you

**Comment by fire-eggs** [comment]
I posted some current screen shots in the wiki - https://github.com/fire-eggs/YAGP/wiki/screens

All pretty crude, very much a work in progress. At this point the programs are mostly for exercising the GEDCOM library, maybe they'll evolve into something bigger someday.

Thanks for asking!
