### ISSUE TITLE
Names in different languages

### ISSUE THREAD

**Issue by Serg-Norseman** [fire-eggs/YAGP#55]
Kevin, you did not saw materials anywhere - how in GEDCOM do people have several names in different languages? It seems that I will have to make a non-standard extension - some tag in the name entry to identify the name language...

I do not know how to do this...

And further. Maybe you saw somewhere the materials on the topic, like I have in the issue 157 (GK).

**Comment by fire-eggs** [comment]
Sergey -
Regarding names in multiple languages, I would suggest using the NAME_TYPE subordinate tag as described in GEDCOM 5.5.1. See section `PERSONAL_NAME_STRUCTURE`. An INDI record can have as many NAME sub-records as you desire; each NAME sub-record can have a NAME_TYPE tag, and that tag _can have any value_.

So for example, using a character from a UK TV series:
```
0 @I1@ INDI
1 NAME Richard /Devere/
2 NAME_TYPE immigrant
1 NAME Bedriche /Poluvitska/
2 NAME_TYPE Birth name, polish?
```

Kevin

**Comment by Serg-Norseman** [comment]
Thank you very much, Kevin! Good answer! I've been working hard lately and have made mistakes and stopped finding the right information. This is angry and I began to seek help...

Thank you!

**Comment by Serg-Norseman** [comment]
I'll think what I want to do. Or rather, what I want to get ...

**Comment by Serg-Norseman** [comment]
`
0 @I1@ INDI
1 NAME Richard /Devere/
2 _LANG English
....
1 NAME Bedriche /Poluvitska/
2 _LANG Czech
`

I like this variant somehow more...

**Comment by fire-eggs** [comment]
>I like this variant somehow more...

Agreed!
